## Vectorization
Instead of for loops we use numpy to do matrix multiplications.

In [3]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
# Compare np.dot to for loop
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print('c value: ',c)
print('Vectorized version: ' + str(1000*(toc-tic))+ "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c+= a[i]*b[i]
print('c value: ',c)
toc = time.time()
print('For loop: ' + str(1000*(toc-tic))+ "ms")

c value:  249748.28011225196
Vectorized version: 1.4290809631347656ms
c value:  249748.28011225257
For loop: 177.02293395996094ms


In [26]:
import math
# e - example

# for loop
v = np.zeros((10, 1))
u = np.zeros((10, 1))
for i in range(10):
    u[i]=math.exp(v[i])

# vectorized version
u = np.exp(v)
print(u)

# other functions
# np.log()
# np.abs()
# np.maximum()
# v**2
# etc.

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


/var/folders/zg/zbbdnsrs6m32y78kjk7bj6_c0000gn/T/ipykernel_16869/567468501.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  u[i]=math.exp(v[i])


## Vectorize logistic regression

In [27]:
# FORWARD STEP
# 1st training example
# z(1) = wTx(1) + b
# a(1) = sigmoid(z(1)) - a is activation
# 2nd training example
# z(2) = wTx(2) + b
# a(2) = sigmoid(z(2))
# etc...
# we can do all of this in one line of code
# Z = [z(1) z(2) ... z(n)] = wTx+[b b ... b] = [wTx(1)+b wTx(2)+b ... wTx(n)+b]
# Z = np.dot(wT, x) + b
# b is (1,1) but it is broadcasted to (1,n)
# A = [a(1) a(2) ... a(n)] = sigmoid(Z)
# BACKPROPAGATION
# dZ = A-Y
# db = 1/m SUM(dZ(i)) = 1/m np.sum(dZ)
# dw = 1/m X dZT

In [28]:
# Implementation
# for iter in range(1000):
    # Z = wTX+b = np.dot(wTX) + b
    # A = Sigmoid(Z)
    # dZ = A - Y
    # dw = 1/m XdZT
    # db = 1/m np.sum(dZ)
    # w := w -alfadw
    # b := b -alfadb

## Broadcasting

In [33]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [41]:
# my solution
(A/A.sum(0))*100

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [39]:
# Lecture
cal = A.sum(axis = 0)
print(cal)

[ 59.  239.  155.4  76.9]


In [40]:
percentage = 100*A/cal.reshape(1,4) # reshape is redundant, it is just added to make sure correct shape is present
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [42]:
A = np.array([[1],
             [2],
             [3]])
A

array([[1],
       [2],
       [3]])

In [43]:
A+100

array([[101],
       [102],
       [103]])

In [45]:
A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [46]:
A + 100

array([101, 102, 103])

In [48]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
B = np.array([100, 200, 300, 400])

In [49]:
A + B

array([[156. , 200. , 304.4, 468. ],
       [101.2, 304. , 352. , 408. ],
       [101.8, 335. , 399. , 400.9]])

In [54]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0]])
B = np.array([[100], [200]])

In [55]:
A + B

array([[156. , 100. , 104.4, 168. ],
       [201.2, 304. , 252. , 208. ]])

In [57]:
# TIPS
a = np.random.randn(5)

In [59]:
a.shape # rank 1 array

(5,)

In [60]:
a

array([-6.46439973e-01,  6.95503553e-01, -6.30829656e-04,  3.13984487e-01,
        6.23981610e-01])

In [61]:
a.T

array([-6.46439973e-01,  6.95503553e-01, -6.30829656e-04,  3.13984487e-01,
        6.23981610e-01])

In [62]:
np.dot(a, a.T)

1.389549535915326

In [63]:
# To make sure it is 5,1 do
a = np.random.randn(5,1) # column vector

In [65]:
np.dot(a, a.T)

array([[ 1.03752861, -0.79955011,  0.28659345, -1.01489218, -0.24614075],
       [-0.79955011,  0.61615687, -0.22085736,  0.78210581,  0.18968331],
       [ 0.28659345, -0.22085736,  0.07916486, -0.28034066, -0.06799073],
       [-1.01489218,  0.78210581, -0.28034066,  0.99274962,  0.24077054],
       [-0.24614075,  0.18968331, -0.06799073,  0.24077054,  0.05839383]])

In [66]:
a = np.random.randn(1,5) # row vector
a

array([[-1.24088624, -1.53074724,  0.75267027, -0.59944269, -1.01705201]])

In [69]:
# assert
assert(a.shape == (1,5))

In [70]:
a = a.reshape((1,5))

In [76]:
a=np.random.randn(3,4) # a.shape=(4,3)a.shape=(4,3)

b=np.random.randn(1,4) # b.shape=(1,3)b.shape=(1,3)

c=a*b

In [77]:
c.shape

(3, 4)

In [78]:
a=np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])

In [79]:
x=np.array([[[1],[2]],[[3],[4]]])
x.shape

(2, 2, 1)

In [80]:
x

array([[[1],
        [2]],

       [[3],
        [4]]])

In [84]:
a=np.array([[1,1],[1,-1]])

b=np.array([[2],[3]])

c=a+b

In [85]:
c

array([[3, 3],
       [4, 2]])